{
 "title": "Main dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total guild count",
   "type": "stat",
   "description": "The total amount of guilds the bot is in",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Guilds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bot_guild_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total user install count",
   "type": "stat",
   "description": "The total amount of user installs for the application",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "User installs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bot_user_install_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Commands used by type",
   "type": "timeseries",
   "description": "The total amount of commands used",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(command_type) (rate(handler_interaction_commands_total{command_type!~\"info|null\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gateway & Handler events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Gateway event rate",
   "type": "stat",
   "description": "The rate of events received by the gateway",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gateway_events_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway events by worker ID",
   "type": "timeseries",
   "description": "The rate of events received on the gateway, grouped by worker ID",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by(worker_id) (rate(gateway_events_received_total{worker_id=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handler events by handler ID",
   "type": "timeseries",
   "description": "The rate of events received on the handler, grouped by handler ID",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum by(handler_id) (rate(handler_events_received_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway events by shard",
   "type": "timeseries",
   "description": "The rate of events received by the gateway, grouped by shard ID",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(shard_id) (rate(gateway_events_received_total{shard_id=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway events by type",
   "type": "timeseries",
   "description": "The rate of events received on the gateway, grouped by type",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum by(type) (rate(gateway_events_received_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interactions by type",
   "type": "timeseries",
   "description": "The rate of interactions received on the handler, grouped by type",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by(type) (rate(handler_interaction_types_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "API request rate",
   "type": "stat",
   "description": "The rate of requests made to the rust API",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API requests by route",
   "type": "timeseries",
   "description": "The rate of requests made to the rust API, grouped by route",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "sum by(route, method) (rate(api_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API requests by response status",
   "type": "timeseries",
   "description": "The rate of requests made to the rust API, grouped by response status",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "sum by(status) (rate(api_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API request cached percentage",
   "type": "stat",
   "description": "The percentage of requests that got a cached response",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * \r\nsum(increase(api_requests_total{cached=\"true\"}[$__range]))\r\n/ \r\nclamp_min(sum(increase(api_requests_total[$__range])), 1)\r\n> 0 or NA",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Anilist API request rate",
   "type": "stat",
   "description": "The rate of requests made to the Anilist API",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(anilist_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API requests by response status",
   "type": "timeseries",
   "description": "The rate of requests made to the anilist API, grouped by response status",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "sum by(status) (rate(anilist_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Popularity statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Most popular anime",
   "type": "bargauge",
   "description": "The most viewed anime over the selected range",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, round(sum by(media_name) (increase(handler_media_commands_total{media_type=\"ANIME\"}[$__range])), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most popular manga",
   "type": "bargauge",
   "description": "The most viewed manga over the selected range",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, round(sum by(media_name) (increase(handler_media_commands_total{media_type=\"MANGA\"}[$__range])), 1))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}